apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: webolith-channels-cleanup
spec:
  # Every 5 minutes, run clean up tasks.
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: webolith-channels-cron
            image: domino14/webolith:{{ BUILD_NUM }}
            command: ["/bin/sh", "-c", "/opt/webolith/scripts/channels_cleanup.sh"]
            env:
              - name: DEBUG
                value: 'off'
              - name: SECRET_KEY
                value: ABCDEFGHIJKLMNOPQRSTUVWXYZ
              - name: PGSQL_DB_NAME
                value: {{ PGSQL_DB_NAME }}
              - name: PGSQL_USER
                value: {{ PGSQL_USER }}
              - name: PGSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: webolith-secrets
                    key: PGSQL_PASSWORD
              - name: PGSQL_HOST
                valueFrom:
                  secretKeyRef:
                    name: webolith-secrets
                    key: PGSQL_HOST
          restartPolicy: OnFailure