kind: Service
apiVersion: v1
metadata:
  name: webolith
  labels:
    app: webolith
spec:
  selector:
    app: webolith
    component: daphne
  ports:
    - port: 8000
      name: daphne-port

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: webolith-daphne-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webolith
        component: daphne
    spec:
      containers:
      - name: webolith-container
        image: domino14/webolith:329

        readinessProbe:
          exec:
            command:
            - cat
            - /opt/webolith/djAerolith/test_requirements.txt
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 5

        lifecycle:
          preStop:
            exec:
              # A hack to try to get 0% downtime during deploys. This should
              # help ensure k8s eventually stops giving this node traffic.
              command: ["sh", "-c", "rm /opt/webolith/djAerolith/test_requirements.txt && sleep 20"]

        env:
          - name: DEBUG
            value: 'off'
          - name: DEBUG_JS
            value: 'off'

          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: DJANGO_SECRET_KEY
      restartPolicy: Always
