pgdb:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: pass
  volumes_from:
    - pgdb_data
  expose:
    - 5432
  ports:
    - 5437:5432

pgdb_data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data
    - /Users/cesar/Downloads:/opt/downloads
# best way to load data into db
# docker-compose up pgdb
# docker exec -it webolith_pgdb_1 bash
# psql -U postgres
# drop database djaerolith;
# create database djaerolith;
# exit out
# then go to /opt/downloads and do psql -U postgres djaerolith < file.sql

app:
  env_file:
    - ./config/local_config.env
  build: .
  working_dir: /opt/webolith/djAerolith
  volumes:
    - .:/opt/webolith:rw
    - ./db:/db
  ports:
    - 8000:8000
  links:
    - pgdb
  external_links:
    - macondo_macondo_1:macondo
  command: python manage.py runserver 0.0.0.0:8000

