pgdb:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: pass
  volumes_from:
    - pgdb_data
  expose:
    - 5432
  ports:
    - 5437:5432

pgdb_data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data

# best way to load data into db
# add volume below to app (mount sql file location as /opt/downloads .e.g)
# then docker exec -it webolith_app_1 bash
# then go to /opt/downloads and do mysql -u root -p djAerolith -h db < file.sql

app:
  env_file:
    - ./config/local_config.env
  build: .
  working_dir: /opt/webolith/djAerolith
  volumes:
    - .:/opt/webolith:rw
    - ./db:/db
    - /Users/cesar/Downloads:/opt/downloads
  ports:
    - 8000:8000
  links:
    - pgdb
  external_links:
    - macondo_macondo_1:macondo
  command: python manage.py runserver 0.0.0.0:8000

