kind: Service
apiVersion: v1
metadata:
  name: webolith
  labels:
    app: webolith
spec:
  selector:
    app: webolith
    component: django
  ports:
    - port: 8000
      name: django-port
  #     nodePort: 31344   # Force a specific port.
  # type: NodePort

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: webolith-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webolith
        component: django
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: webolith-container
        # XXX: DON'T USE LATEST ON PROD.
        image: domino14/webolith:7
        readinessProbe:
          exec:
            command:
            - cat
            - /opt/webolith/djAerolith/test_requirements.txt
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 5
        lifecycle:
          preStop:
            exec:
              # A hack to try to get 0% downtime during deploys. This should 
              # help ensure k8s eventually stops giving this node traffic.
              command: ["sh", "-c", "rm /opt/webolith/djAerolith/test_requirements.txt && sleep 20"]

        env:
          - name: DEBUG
            value: 'off'
          - name: DEBUG_JS
            value: 'off'
          - name: PGSQL_DB_NAME
            value: djaerolith
          - name: PGSQL_USER
            value: postgres
          # XXX: This doesn't matter? We should collectstatic outside
          # the container.
          - name: STATIC_ROOT
            value: /opt/webolith_static
          - name: USE_MX
            value: 'off'
          - name: USE_GA
            value: 'off'
          - name: USE_FB
            value: 'off'
          - name: USE_UV
            value: 'off'
          - name: NOCAPTCHA
            value: 'on'
          - name: MACONDO_ADDRESS
            value: http://macondo:8088
          - name: RECAPTCHA_SSL
            value: 'off'
          - name: WORD_DB_LOCATION
            value: /db
          - name: AWS_ACCESS_KEY_ID
            value: AKIAJIHDRRVM5ZIRNZBA
          - name: SOCIAL_AUTH_FACEBOOK_KEY
            value: '10154121300449470'
          - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
            value: 876672922819-a953537d9jga3a69c8ifl1qb3cgfnlsa.apps.googleusercontent.com

          # Secrets follow
          - name: PGSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: pgsql_password
          - name: PGSQL_HOST
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: pgsql_host
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: django_secret_key
          - name: EMAIL_PW
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: mailgun_pw
          - name: RECAPTCHA_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: recaptcha_private_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: aws_secret_access_key
          - name: SOCIAL_AUTH_FACEBOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: social_auth_facebook_secret
          - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
            valueFrom:
              secretKeyRef:
                name: webolith-secrets
                key: social_auth_google_oauth2_secret

        volumeMounts:
        # This should be the same as the WORD_DB_LOCATION env var.
        - mountPath: /db
          name: word-db-data
        - mountPath: /opt/webolith_static
          name: webolith-static
      volumes:
      - name: word-db-data
        hostPath:
          # Change this path to the relevant db path.
          path: /Users/cesar/coding/webolith/db
      - name: webolith-static
        hostPath:
          path: /Users/cesar/coding/webolith/kubernetes/webolith_static
      restartPolicy: Always
