apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: webolith-daily-cleanup
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: webolith-cron
            image: domino14/webolith:7
            command: ["/bin/sh", "-c", "/opt/webolith/scripts/dailyCleanup.sh"]
            env:
              - name: DEBUG
                value: 'off'
              - name: AWS_ACCESS_KEY_ID
                value: AKIAJIHDRRVM5ZIRNZBA
              - name: SECRET_KEY
                value: ABCDEFGHIJKLMNOPQRSTUVWXYZ
              - name: PGSQL_DB_NAME
                value: djaerolith
              - name: PGSQL_USER
                value: postgres
              - name: BACKUP_BUCKET_SUFFIX
                value: "-local"
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: webolith-secrets
                    key: aws_secret_access_key
              - name: PGSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: webolith-secrets
                    key: pgsql_password
              - name: PGSQL_HOST
                valueFrom:
                  secretKeyRef:
                    name: webolith-secrets
                    key: pgsql_host
          restartPolicy: OnFailure